server:
  port: 7020
  servlet:
    context-path: /business

spring:
  application:
    name: fighting-business

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

